name: Create Release tag
on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: update semver tag
      id: semver_tag
      run: |
        ls -lah && chmod 755 semver_tag.sh
        tag=sh ./semver_tag.sh
        echo $tag 
        echo "::set-output name=TAG_NAME::$tag"
        
    - name: debug
      run: echo ${{ steps.semver_tag.outputs.TAG_NAME }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.semver_tag.outputs.TAG_NAME }}
        release_name: ${{ steps.semver_tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false
