name: Create Release tag
on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: update semver tag
      id: semver_tag
      run: |
        chmod 755 semver_tag.sh
        tag=$(./semver_tag.sh)
        echo $tag >> $GITHUB_OUTPUT

    - name: Create Release
      run: echo ${{ steps.semver_tag.outputs.tag }}
