name: Create Release tag
on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: update semver tag
      id: semver_tag
      run: |
        echo "::set-output name=TAG_NAME::$(/bin/bash ./semver_tag.sh)"

    - name: Create Release
      run: echo ${{ steps.semver_tag.outputs.TAG_NAME }}
