
name: Terrsform Pull request test
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          terraform -version
          echo here is the terraform version
          terraform init
          terraform fmt
