name: Terraform fmt Check

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    name: Terraform-fmt lint
    
    runs-on: ubuntu-latest
    
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    
    - name: terraform fmt check
      uses: dflook/terraform-fmt-check@v1
      
    - name: Run on Fail fmt
      if: failure()
      run: |
        echo "fmt failed fix the terraform files"
        exit 1
