name: Terraform fmt Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Terraform-fmt lint
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files 
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            sh script/fmt-check.sh
          done
