name: Terraform fmt Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Terraform-fmt lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sh script/fmt-check.sh