name: Terraform fmt Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Terraform-fmt lint
    
    runs-on: ubuntu-latest
    
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    
    - name: terraform fmt
      uses: dflook/terraform-fmt-check@v1
