on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
name: Release Artifacts

jobs:

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: getting project dir path
        run: |
          ls -la
          project-dir = $(pwd)
          echo ${pwd}
       
      - name: Step 3 - Use the Upload Artifact GitHub Action
        run: gh release create ${{ github.ref }} --generate-notes
        
