on:
  push:
    tags:
      - '*'

name: Release Artifacts

jobs:

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
